#!/usr/bin/env node
// Generates an @dsCard shim next to every specimen source so Claude Design's
// scanner can see it (it reads the working tree, not dist/). Output is
// committed but never hand-edited — rerun this script after changing a
// specimen's card metadata, its default export name, or adding/removing a file.
import * as esbuild from 'esbuild';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// This script lives at <root>/.claude/skills/generate-cards/generate-cards.ts —
// three levels below the repo root.
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');

// Keep in sync with package.json's react/react-dom major.
const REACT = '18.3.1';
const PHOSPHOR = '2.1.1';
const BANNER = 'GENERATED by the generate-cards skill — do not edit. Source:';

interface Card {
  group: string;
  viewport: [number, number];
  name: string;
  subtitle: string;
  padding?: string;
}

async function findFiles(dir: string, matchExt: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(d: string) {
    for (const entry of await fs.readdir(d, { withFileTypes: true })) {
      const p = path.join(d, entry.name);
      if (entry.isDirectory()) await walk(p);
      else if (p.endsWith(matchExt)) out.push(p);
    }
  }
  await walk(dir);
  return out.sort();
}

// Same approach as scripts/build.ts importSpecimenModule: bundle to a temp
// .mjs written inside the repo so bare `import 'react'` resolves against this
// project's node_modules.
async function importModule(file: string): Promise<Record<string, unknown>> {
  const result = await esbuild.build({
    entryPoints: [file],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'node',
    jsx: 'automatic',
    external: ['react', 'react/jsx-runtime', 'react-dom', 'react-dom/server'],
    logLevel: 'silent',
  });
  const tmpDir = path.join(root, '.build-tmp');
  await fs.mkdir(tmpDir, { recursive: true });
  const tmpFile = path.join(tmpDir, `ds-card-${process.pid}-${Math.random().toString(36).slice(2)}.mjs`);
  await fs.writeFile(tmpFile, result.outputFiles[0].text);
  try {
    return await import(pathToFileURL(tmpFile).href);
  } finally {
    await fs.unlink(tmpFile);
  }
}

// Resolve card metadata STRUCTURALLY, not by hardcoded name: some files could
// export `card`, others `<name>Card` — don't assume only one convention.
function resolveCard(mod: Record<string, unknown>, rel: string): Card {
  if (mod.card) return mod.card as Card;
  const named = Object.keys(mod).filter((k) => /Card$/.test(k) && k !== 'default');
  if (named.length === 1) return mod[named[0]] as Card;
  throw new Error(
    `${rel}: expected exactly one card metadata export (\`card\` or \`*Card\`), found ${named.length}` +
      (named.length ? `: ${named.join(', ')}` : '')
  );
}

// The Claude Design compiler exposes the default export under its function
// name, so the shim must mount that exact identifier.
function resolveExportName(mod: Record<string, unknown>, rel: string): string {
  const name = (mod.default as { name?: string } | undefined)?.name;
  if (!name) throw new Error(`${rel}: default export must be a named function`);
  return name;
}

function shim(card: Card, exportName: string, base: string, rel: string, phosphor: boolean): string {
  const [w, h] = card.viewport;
  const padding = card.padding ?? '18px';
  const icons = phosphor
    ? `\n<link rel="stylesheet" href="https://unpkg.com/@phosphor-icons/web@${PHOSPHOR}/src/light/style.css">` +
      `\n<link rel="stylesheet" href="https://unpkg.com/@phosphor-icons/web@${PHOSPHOR}/src/thin/style.css">`
    : '';
  // The namespace suffix is the Claude Design project id, so resolve it by
  // prefix — hardcoding it would break any fork of this system.
  return `<!-- @dsCard group="${card.group}" viewport="${w}x${h}" name="${card.name}" subtitle="${card.subtitle}" -->
<!-- ${BANNER} ${rel} -->
<!doctype html><html lang="en"><head><meta charset="utf-8">
<link rel="stylesheet" href="${base}/styles.css">${icons}
<script src="https://unpkg.com/react@${REACT}/umd/react.production.min.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/react-dom@${REACT}/umd/react-dom.production.min.js" crossorigin="anonymous"></script>
<script src="${base}/_ds_bundle.js"></script>
</head><body style="margin:0;padding:${padding};background:var(--surface-page);font-family:var(--font-sans);overflow:hidden">
<div id="root"></div>
<script>
var NS = window[Object.keys(window).find(function (k) { return k.indexOf('LumenisDesignSystem') === 0 })];
ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(NS.${exportName}));
</script>
</body></html>
`;
}

async function generate() {
  const sources = [
    ...(await findFiles(path.join(root, 'guidelines'), '.tsx')).map((f) => ({ file: f, phosphor: false })),
    ...(await findFiles(path.join(root, 'components'), '.specimen.tsx')).map((f) => ({ file: f, phosphor: true })),
  ];

  const written = new Set<string>();
  for (const { file, phosphor } of sources) {
    const rel = path.relative(root, file).split(path.sep).join('/');
    const mod = await importModule(file);
    const card = resolveCard(mod, rel);
    const exportName = resolveExportName(mod, rel);
    const dir = path.dirname(file);
    const base = path.relative(dir, root).split(path.sep).join('/') || '.';
    // buttons.specimen.tsx -> buttons.card.html; colors-primary.tsx -> colors-primary.card.html
    const slug = path.basename(file, '.tsx').replace(/\.specimen$/, '');
    const outFile = path.join(dir, `${slug}.card.html`);
    await fs.writeFile(outFile, shim(card, exportName, base, rel, phosphor));
    written.add(outFile);
    console.log(`  ${path.relative(root, outFile)}  →  NS.${exportName}`);
  }

  // Drop orphans: a .card.html whose specimen source no longer exists.
  for (const dir of ['guidelines', 'components']) {
    for (const existing of await findFiles(path.join(root, dir), '.card.html')) {
      if (written.has(existing)) continue;
      await fs.unlink(existing);
      console.log(`  removed orphan ${path.relative(root, existing)}`);
    }
  }

  await fs.rm(path.join(root, '.build-tmp'), { recursive: true, force: true });
  console.log(`${written.size} card shims generated.`);
}

await generate();
